name: Build with JDK8

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build-on-jdk8:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Publish Test Report
        if: ${{ always() }}
        uses: mikepenz/action-junit-report@v3
        with:
          check_name: JDK8 result
          report_paths: '**/build/test-results/test/TEST-*.xml'
